# Generated by Django 4.2.16 on 2025-02-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forexdata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='indexdata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='forexdata',
            unique_together={('pair', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='indexdata',
            unique_together={('ticker', 'date')},
        ),
    ]
